### ISSUE TITLE
Invalid JSON format?

### ISSUE THREAD

**Issue by davidaha** [wp-net/WordPressXF#6]
After changing    WordpressUrl = "https://www.thewaltdisneycompany.com/wp-json/";

Getting NewsViewModel | LoadPostsAsync | Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'WordPressPCL.Models.BadRequest' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

The url looks well formed via curl and browser.   

There is one other error in application output: 

[Mono] AOT: image 'System.Numerics.dll.so' not found: dlopen failed: library "/data/app/com.companyname.WordPressXF-0sYXZCSrP6Fs4zi0y2ebiQ==/lib/x86/libaot-System.Numerics.dll.so" not found

Thoughts?

Visual Studio 7.6.6

**Comment by tsjdev-apps** [comment]
Hi @davidaha,

thanks for using the project. I have to inform you that the functionality to access the posts is not allowed on the provided webpage. This is the reason why the app is failing to access the posts. Can you try it with a different url, please?

The other error message can be ignored, because for some DLL files there is no AOT Version available and than it will use the JIT Version. So nothing to worry about, as you can see [here](https://bugzilla.xamarin.com/show_bug.cgi?id=42933).

Greetings,
 tsjdev-apps

**Comment by tscholze** [comment]
Hi @tsjdev-apps,

I've the same issue as @davidaha for other blogs.

There is a "official" issue at the WordPressPCL repo: https://github.com/wp-net/WordPressPCL/issues/144

**Comment by tsjdev-apps** [comment]
Hi,

will take a look together with @ThomasPe  to find a solution for this. I will update this issue with further information.

**Comment by tsjdev-apps** [comment]
With the new beta version of the WordPressPCL-Package most blogs are now accessible with this app as well. 

The only issue is regarding the Disney Blog, because they deactivated the endpoints to access the posts. So here we are unable to give support.
